### PR TITLE
Adding UDP traffic profile options for variable packet size and delay between packets

### PR DESCRIPTION
**Pull request by davidBar-On**
* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies:
Master

* Issues fixed (if any):
None - new functionality

* Brief description of code changes (suitable for use as a commit message):
Adding options to support different UDP traffic profiles to test behavior under different network conditions (not just throughput): variable packet length (-l) - random or fixed delta (--step), delay (--sleep) between packets or between burst of packets (--bundle).

### CODE REVIEW

**Comment by davidBar-On** [comment]
Hi, the continuous integration of this pull request (#975) is failing on:
    ....
    config.status: error: cannot find input file: `Makefile.in'
    The command "./configure && make && make check" exited with 1.

I would appreciate help in identifying what is the reason for the problem.
Thanks

**Comment by davidBar-On** [comment]
Closed because of error in the  continuous integration which I was not able to resolve.  Sent a new pull request (#1004) with the same changes but from a new branch that hopefully will not have these  continuous integration issues.

**Comment by spick002** [comment]
Hi davidBar-On,
I can see how, by use of a traffic model/profile, iPerf3 could allow varying packet size, delay, and throughput/bandwidth. 
This would be very useful for a number of cases, including a potential project I have in the works.  
I know it's been a few years, but do you know if the ability to vary any of these throughout a single iPerf3 run have been integrated?

**Comment by davidBar-On** [comment]
Hi @spick002,
None of these options are integrated into iperf3.  Note that I submitted some other PRs for these changes.  Therefore PR #1075 is the PR to be used if required.  If you are interested, I can try to rebase it to catch up with the latest iperf3 version (3.16).

Also, note that PR #1343 is for just the gap delay between packets (with improved implementation).  This is sufficient for varying throughput, but not for varying packets sizes.  I can also try to rebase this one.

**Pull request closed without merging**
