### PR TITLE
Add support for OpenBSD systems which have TCP_INFO implemented.

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Comment by bmah888** [comment]
Thanks for the PR! We're having a little testing this. On an OpenBSD 7.1/amd64 system (latest available download from openbsd.org) there doesn't appear to be any `struct tcpinfo` structure or `TCP_INFO` socket option. So this feature won't get detected at configure time, and these code changes won't do anything. Are we testing on the wrong platform?

**Comment by brad0** [comment]
TCP_INFO support was added in -current. 7.2 has been tagged and the release is days away. You can also use a -current snap that is now past 7.2 if you want.

https://ftp.openbsd.org/pub/OpenBSD/snapshots/packages/

**Comment by brad0** [comment]
The 7.2 release is now out.

**Review by bmah888 — APPROVED** [review]
Compiles and runs correctly (in limited testing) on OpenBSD 7.2. Thanks for the PR!  (I will merge this when I get some iperf3 time.)

**Comment by brad0** [comment]
Thanks.

**Pull request merged**
