### PR TITLE
Fix for issue 1215 - add TCP  option

### PR DESCRIPTION
**Pull request by davidBar-On**
* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies:
3.11

* Issues fixed (if any):
#1215

* Brief description of code changes (suitable for use as a commit message):

Suggested fix for issue #1215 - adding `snd-timeout` option.  Used by a sender to set TCP `TCP_USER_TIMEOUT ` socket option, so if TCP send for that time, session is terminated.  Applied also for the Control Socket.  (Note: I tried to find existing iperf3 option that can be used, instead of adding a new option, but there doesn't seem to be such option.)

Useful to reduce TCP timeout in cases there is a problem with the interface to the receiver (such as cell phone IP address change as in #1215).

Not sure how to resolve the conflic in `configure`.  The file was changed to add the `HAVE_TCP_USER_TIMEOUT`, but in WSL Ubunto I use, `autoconf 2.69` is available, not 2.71.

### CODE REVIEW

**Comment by bmah888** [comment]
Thanks for the pull request! I'll give it a look.

About the `configure` part...don't worry about including changes to `configure` in the pull request. We can regen that with autoconf-2.71 on either macOS or FreeBSD after it's been merged. I was looking for changes to `configure.ac`, which is the source for `configure`, but didn't see that file among the listed files in the pull request?

We probably need to do a manual page update also.

**Comment by davidBar-On** [comment]
Added the modified `configure.ac` (was not included originally by mistake).

**Comment by bmah888** [comment]
Thanks for the PR! I'm going to merge this as it stands now, then do some follow-up commits for regenerating the configure scripts, etc. and some manpage, etc. updates.

**Comment by zokl** [comment]
Thank you very much for your PR.

**Pull request merged**
