### PR TITLE
fix(cygwin): Fix compile error where CPU_SETSIZE isn't defined.

### PR DESCRIPTION
**Pull request by bmah888**
Possible fix for #944.

### CODE REVIEW

**Comment by RomelSan** [comment]
There is an error here:
File: iperf_api.c
Line: 4084
However replacing "CPU_SETSIZE" with "__CPU_SETSIZE" compiles fine on cygwin.
```
iperf_api.c: In function ‘iperf_clearaffinity’:
iperf_api.c:4084:21: error: ‘CPU_SETSIZE’ undeclared (first use in this function); did you mean ‘__CPU_SETSIZE’?
     for (i = 0; i < CPU_SETSIZE; ++i)
                     ^~~~~~~~~~~
                     __CPU_SETSIZE
```
Cygwin version: Cygwin 3.1.2 build 2.897
On Windows Server 2019 and Windows 10 1909 x64

**Comment by bmah888** [comment]
@RomelSan The problem with your proposed change is that it makes all platforms reference `__CPU_SETSIZE`, even those that were working fine with `CPU_SETSIZE` before.  In my version of the change (which is in this pull request), I wanted to just be sure that `CPU_SETSIZE` got defined appropriately on Cygwin, but for some reason it isn't quite working.  I'm trying to not change the behavior of Linux, *BSD, and macOS, primarily because we have declared that those platforms are officially supported and Cygwin is not.

**Comment by RomelSan** [comment]
It worked by moving the IF.
File: iperf_api.c
```
#if defined(HAVE_CPUSET_SETAFFINITY)
#include <sys/param.h>
#include <sys/cpuset.h>
#endif /* HAVE_CPUSET_SETAFFINITY */

#if defined(__CYGWIN__) || defined(_WIN32) || defined(_WIN64) || defined(__WINDOWS__)
  #define CPU_SETSIZE __CPU_SETSIZE
#endif /* __CYGWIN__ */

#if defined(HAVE_SETPROCESSAFFINITYMASK)
#include <Windows.h>
#endif /* HAVE_SETPROCESSAFFINITYMASK */
```

**Comment by RomelSan** [comment]
@bmah888 Hi.
Check post #944 , tested and working.
😀

**Pull request merged**
