### PR TITLE
Issue 1157 take 2

### PR DESCRIPTION
**Pull request by bmah888**
* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies: `master`

* Issues fixed (if any): #1157 

* Brief description of code changes (suitable for use as a commit message):

Builds on @davidBar-On work in PR #1180 to implement functionality described in #1157.

### CODE REVIEW

**Comment by bmah888** [comment]
@davidBar-On @TheRealDJ if you could take a look at this and comment, that'd be appreciated!

**Comment by TheRealDJ** [comment]
Code looks good.
Testing Results (masked IPs and Interfaces):
```
./iperf3 --client ${IPERF_SERVER_GLOBAL}
<Test runs as expected>

./iperf3 --client ${IPERF_SERVER_GLOBAL}%${IPERF_SERVER_INT}
p ${IPERF_SERVER_GLOBAL} p1 ${IPERF_SERVER_INT}
<Test runs as expected>

./iperf3 --client ${IPERF_SERVER_LL}%${IPERF_SERVER_INT}
p ${IPERF_SERVER_LL} p1 ${IPERF_SERVER_INT}
IPv6 link local address literal detected
<Test runs as expected>

./iperf3 --client ${IPERF_SERVER_LL}
iperf3: error - unable to connect to server: Invalid argument
```
Looks like the code sets the bind address and interface for `--client GLOBAL%INTERFACE`, but the output doesn't indicate if any binding occurred. Maybe somewhere in the JSON output could be an indication if any specific binding was done (in the case of `--client ADDRESS%DEV`, `--bind ADDRESS%DEV` or `--bind-dev DEV`).

Also, I'd assume that the added iperf_print calls are for testing purposes? They break JSON output.

DJ

**Comment by TheRealDJ** [comment]
I also submitted https://github.com/esnet/iperf/pull/1211 to fix the 2 compile warnings I was getting in the testing process.

**Comment by davidBar-On** [comment]
I sent one comment (including two potential issues). 
There is one difference with iperf2 that I want to point out.  iperf2 is using two different variables for the `device` from `-B` and `-c`.  In addition, setting the device on the client is allowed only by `-c` and on the server only by `-B`.  E.g. see [this warning](https://sourceforge.net/p/iperf2/code/ci/master/tree/src/Settings.cpp#l1657). I didn't find any problem in this PR related code, and I believe that iperf2 uses two separate variables for the device because it doesn't have the `--bind-dev` option. However I am noting this instead I missed something.

**Review by swlars — APPROVED** [review]

**Comment by bmah888** [comment]
> I sent one comment (including two potential issues). There is one difference with iperf2 that I want to point out. iperf2 is using two different variables for the `device` from `-B` and `-c`. In addition, setting the device on the client is allowed only by `-c` and on the server only by `-B`. E.g. see [this warning](https://sourceforge.net/p/iperf2/code/ci/master/tree/src/Settings.cpp#l1657). I didn't find any problem in this PR related code, and I believe that iperf2 uses two separate variables for the device because it doesn't have the `--bind-dev` option. However I am noting this instead I missed something.

Good observation @davidBar-On, I think this is basically just differing implementations of the "bind a socket to an interface" functionality between iperf2 and iperf3. Hopefully the addition of the "%" shortcut won't create any confusion, and it would work the same between the two programs. Thanks!

**Comment by bmah888** [comment]
> Also, I'd assume that the added iperf_print calls are for testing purposes? They break JSON output.

@TheRealDJ , yep, those should been (and now are) hidden behind the debug flag. Thanks for catching that!

Have to think a bit about what else we might want to propagate into the JSON, might be a good future enhancement.

**Pull request merged**
