### PR TITLE
Auto adjustment of test-end condition for file-transfer

### PR DESCRIPTION
**Pull request by hanvari**
In file transfer mode (-F), if no test-end condition is set,
(bytes, blocks, duration), it will automatically adjust it to
file size (in bytes).
If call to stat() fails, it will skip setting the bytes count, hence defaulting to duration mode (10 seconds).

* Version of iperf3 to which this pull request applies: `master`

* Issues fixed (if any): N/A

* Brief description of code changes (suitable for use as a commit message):

**Auto adjustment of test-end condition for file-transfer**

In file transfer mode (-F), if no test-end condition is set,
(bytes, blocks, duration), it will automatically adjust it to
file size (in bytes).
If call to stat() fails, it will skip setting the bytes count, hence defaulting to duration mode (10 seconds).

### CODE REVIEW

**Comment by hanvari** [comment]
@bmah888 Hi Bruce, this is a minor adjustment for file transfer mode, and only depends on a POSIX `stat()` library function.
Is there a reason it is not merged yet?

**Comment by bmah888** [comment]
> @bmah888 Hi Bruce, this is a minor adjustment for file transfer mode, and only depends on a POSIX `stat()` library function.
> Is there a reason it is not merged yet?

I can't think of a reason in particular...most recently I've been on vacation but that doesn't excuse me sitting on this PR for the time before that, apologies! I'll try to look at this as I'm getting caught up.

**Review by bmah888 — COMMENTED** [review]
What happens if there's an error in the stat(2) system call?

**Comment by hanvari** [comment]
> What happens if there's an error in the stat(2) system call?

PR updated to appropriately handle stat() error.
If error happens, it will skip setting the bytes count, hence defaulting to duration mode (10 seconds).

**Review by bmah888 — APPROVED** [review]
Thanks, looks pretty good!

**Pull request merged**
