### PR TITLE
Close control socket and data stream sockets when client is disconnected

### PR DESCRIPTION
**Pull request by dmdailey**
The server will hang the control socket if the client is disconnected (pull the cable) in the middle of a test.  The stream sockets are also left open indefinitely.  Use patch from user mkall to close the control socket and add the closure of the data sockets as well when the test runs for more than 5 seconds over its duration.

### CODE REVIEW

**Comment by rpodgorny** [comment]
i'm also being hit by this. can you please merge? thank you...

**Comment by bmah888** [comment]
Thanks for the pull request!  I need to go look at this.  The problem where the client just disappears is definitely one that the server needs to handle better than it does.

**Comment by bmah888** [comment]
This PR might also solve #378.

**Comment by bmah888** [comment]
Note to self:  To test this functionality, begin running a test and then suspend the client so it can't finish.

**Comment by bmah888** [comment]
Merged to 3.1-STABLE.

**Comment by inesmll** [comment]
I have installed version 3.7 on both client and server machines and the problem persists, both with TCP and UDP connections. The server just won't stop and/or restart when the client disconnects... I'm breaking the connection *before* the test duration ends and I'm using a Alpine machine (client) and a OpenWrt machine (server). I have not found any information about a possible server timeout in the iperf documentation. Am I missing something, or do other people have the same problem?

**Pull request merged**
