### PR TITLE
Add required RSA header for OpenSSL

### PR DESCRIPTION
**Pull request by pprindeville**
Fixes cross-compilation issues under certain buildroot configurations (like LEDE).

### CODE REVIEW

**Comment by bmah888** [comment]
Just asking for my own information...  What's broken before this change?  Like under what circumstances does the build not work?  Just cross-compiling?  Or something else?

**Comment by pprindeville** [comment]
I've only done cross-compiling so I can't say if it builds natively or not.

**Comment by bmah888** [comment]
OK fair enough.  Native compiling works fine on all the supported platforms, which is why your PR was a bit of a surprise.  I'll merge this PR a little later today (have to go to meetings) but just for my reference if you got an error message when trying cross-compile, could you add that as as comment here?  Thanks!

**Comment by pprindeville** [comment]
> [...] but just for my reference if you got an error message when trying cross-compile, could you add that as as comment here? Thanks!

Sure, will do that in the future.

**Comment by bmah888** [comment]
Cool.  Thanks for the PR!

**Pull request merged**
