### PR TITLE
Free descriptor when force exit from function 

### PR DESCRIPTION
**Pull request by maks-mishin**
* Development branch: master

* Issues fixed: free resource descriptor

* Brief description of code changes: free descriptor when force exit from function to avoid descriptor leak(CWE-403).

### CODE REVIEW

**Comment by ProjectMutilation** [comment]
in this case better just add `close(s)` in `if (Nread(s, cookie, COOKIE_SIZE, Ptcp) < 0)` statement

**Comment by maks-mishin** [comment]
@ProjectMutilation, yes, it's more concise.

**Comment by ProjectMutilation** [comment]
Look good to me

**Review by bmah888 — APPROVED** [review]
Thanks for the PR, good fix.

**Pull request merged**
