### PR TITLE
Provide a "--disable-profiling" option with configure 

### PR DESCRIPTION
**Pull request by tersonalpriathlete**
to turn off profiling flags + Bump to autotools 1.16.1

* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies: master

* Issues fixed (if any): #749 

* Brief description of code changes (suitable for use as a commit message):
Provide a command line option with the configure script to disable profiling flags for gprof. (--disable-profiling)

### CODE REVIEW

**Comment by bmah888** [comment]
Thanks for the pull request...I've been wondering how to do this.

For future reference it's probably easiest to just submit changes to the files such as `configure.ac` and `Makefile.am`.  After merging we'll re-run `bootstrap.sh` to regenerate the `Makefile.in`, etc. files.  I admit we didn't communicate that.

Haven't really had a chance to play with the change yet but looking forward to it.

**Comment by bmah888** [comment]
I just tried this out...even if I use `--disable-profiling`, it still tries to build `iperf3-profile`, even without the profiling goop.  Going to try something, will add another comment if this works.

**Comment by tersonalpriathlete** [comment]
thanks @bmah888 - I did not look into the bootstrap shell script. Would have made a few things much simpler. I'll have a look at this and submit a new PR with just the configure.ac and makefile.am changes.
Do you want to go ahead and reject this PR to clear the decks for that ?

**Comment by bmah888** [comment]
Sure I can close this PR (I guess you have done that too?).  Looking forward to seeing the new version.  Thanks for working on this, as you probably know a number of people have asked for it.

**Comment by rollingslack** [comment]
#763 is the new PR !

**Pull request closed without merging**
