### PR TITLE
Adding feature to support TCP_MD5SIG option for Linux. [OLD, newer pull req #350]

### PR DESCRIPTION
**Pull request by critindirecx**
Signed-off-by: Tejas Wanjari <tejaswanjari@gmail.com>

### CODE REVIEW

**Comment by critindirecx** [comment]
Any comments?

This TCP option is not available to test in any networking tool. I hope it would be good to have it in the mainline. If there are any suggestions or comments, please let me know, I would be glad to help. Thanks.

**Comment by bmah888** [comment]
Thanks for sending the pull request!  I think this is a useful addition to have.  One concern I have about the patch is that there appear to be a lot of whitespace changes (specifically reindented lines), which makes it harder to figure out what the actual functional code changes are.

**Comment by critindirecx** [comment]
Sorry for that, I will re-submit a pull request removing the unneeded whitespace changes.

If there is a formatting-tool that is followed for the codebase, please let me know.

**Comment by critindirecx** [comment]
I have submitted another pull request, that does not contain uneeded whitespace changes: https://github.com/esnet/iperf/pull/350

Let me know.

**Comment by bmah888** [comment]
Superceded by #350.

**Pull request closed without merging**
