### PR TITLE
IP dont fragment support

### PR DESCRIPTION
**Pull request by davidBar-On**
* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies:
3.9+

* Issues fixed (if any):
#1107

* Brief description of code changes (suitable for use as a commit message):

Adding support for setting IP dont-fragment flag, by adding `--dont-fragment` option.  (There is an option of adding value to this option to allow setting do-fragment, but decided not to do that since it may not be required and it complicates the compatibility testing for the different environments.)

The option works well for **Windows** using CigWin.  I don't have test environment for **Unix** (BSD, etc.).

For **Linux**, for some reason my system always set the Don't Fragment flag, so I was not able to test whether setting the option works. However, I tested that that the opposite works - asking to not set the flag (`IP_PMTUDISC_DONT`).  Therefore I believe that asking to set the flag (`IP_PMTUDISC_DO`), which is what is in the code, also works o.k.

### CODE REVIEW

**Comment by bmah888** [comment]
Thanks for the PR! I've been looking at this, as you can probably tell from me flailing around with the conflict resolution tool in the Github Web UI.

I have some medium-sized changes to suggest on top of this PR, mostly having to do with the fact that software portability is hard and dealing with the IP DF socket options isn't particularly portable. So I ended up refactoring conditional compilation and doing some autoconf goop that conditionalizes argument parsing and help text, among other things.

Still being a relative Github newbie, what's the right way for us to coordinate this? I can do comments on your PR but that's going to be a little clumsy due to the scale of the changes. It feels kind of wrong to just close your PR and start over (although I admit I've done that in the past). Any suggestions / hints?

**Comment by bmah888** [comment]
Also just noting here that the way to turn off the Linux default DF behavior is:
```
sysctl net.ipv4.ip_no_pmtu_disc=1
```
This then can be overridden on a per-socket basis via the socket option.

**Comment by davidBar-On** [comment]
> I ended up refactoring conditional compilation and doing some autoconf goop that conditionalizes argument parsing and help text, among other things.

From searching the Internet I was hopping that Linux is the only exception .... Make sure to keep the non-Linux case at least for Windows.

>Still being a relative Github newbie, what's the right way for us to coordinate this? I can do comments on your PR but that's going to be a little clumsy due to the scale of the changes. It feels kind of wrong to just close your PR and start over (although I admit I've done that in the past). Any suggestions / hints?

I am also Github newbie.  From what I read [here](https://stackoverflow.com/questions/39061191/is-it-possible-to-change-other-peoples-code-in-pull-requests-github) you should be able to pull the branch from by fork repository: "**https://github.com/davidBar-On/iperf/tree/issue-1107-ip-dont-fragment-support**" (I set the permission). Then you can make the changes and push them back to my repository.  That should be the same as if I did the changes.

I never tried that, so don't know if it works.  If not, If not, I have no problem that you will close the PR and open new one.

**Comment by bmah888** [comment]
> > I ended up refactoring conditional compilation and doing some autoconf goop that conditionalizes argument parsing and help text, among other things.
> 
> From searching the Internet I was hopping that Linux is the only exception .... Make sure to keep the non-Linux case at least for Windows.

Right...the non-Linux case is good for *BSD, et al. so it will definitely stay.  The other case is macOS, which doesn't support either mechanism as far as I can tell (and that is one of our supported platforms).

> > Still being a relative Github newbie, what's the right way for us to coordinate this? I can do comments on your PR but that's going to be a little clumsy due to the scale of the changes. It feels kind of wrong to just close your PR and start over (although I admit I've done that in the past). Any suggestions / hints?
> 
> I am also Github newbie. From what I read [here](https://stackoverflow.com/questions/39061191/is-it-possible-to-change-other-peoples-code-in-pull-requests-github) you should be able to pull the branch from by fork repository: "**https://github.com/davidBar-On/iperf/tree/issue-1107-ip-dont-fragment-support**" (I set the permission). Then you can make the changes and push them back to my repository. That should be the same as if I did the changes.
> 
> I never tried that, so don't know if it works. If not, If not, I have no problem that you will close the PR and open new one.

I'll try that, thanks. This will be good to make sure that my code changes don't break on Windows/Cygwin (which is a platform I cannot test).

**Comment by bmah888** [comment]
I've pushed something to your branch (thank you for permissions) that I think will work, need to do some more testing across the various supported platforms (Linux, macOS, and FreeBSD).

**Comment by bmah888** [comment]
Finally got everything working on all the platforms I support. Hopefully Windows/Cygwin still works?

**Comment by davidBar-On** [comment]
Windows/Cygwin is defining `IP_DONTFRAGMENT` and not `IP_DONTFRAG`.  Therefore the following changes are needed.  I tested these changes and they work o.k. (I am not pushing the changes as something got wrong with my local git branch after pulling your changes, so I don't want to cause issues to the PR).

1. **configure**: `#ifdef IP_DONTFRAGMENT` should be added, the same as for `IP_DONTFRAG` and `IP_MTU_DISCOVER`.

2. **sec/iperf_api.c**: the `#if defined(IP_DONTFRAG)` should be be duplicated, with using `IP_DONTFRAGMENT` for both the `#if defined` and the `setsockopt` option.

**Comment by bmah888** [comment]
I think I fixed this for Windows now, please let me know if this works. Note that I added some more checking to be sure we only try this with UDP/IPv4 tests.

While testing, I discovered that this doesn't work right with `--reverse`. I think this might be related to #638, at least the situation is somewhat similar (trying to set IPv4-specific socket options on an IPv6 socket that has an IPv4 mapped address). I don't necessarily need to hold up this PR for that problem, since it seems to exist with other features and a general solution to the problem might make `--dont-fragment` work as well.

**Comment by davidBar-On** [comment]
@bmah888, I have tested the changes and they work fine under Windows Cygwin.

**Pull request merged**
