### PR TITLE
Update cjson

### PR DESCRIPTION
**Pull request by swlars**
_PLEASE NOTE the following text from the iperf3 license.  Submitting a
pull request to the iperf3 repository constitutes "[making]
Enhancements available...publicly":_

```
You are under no obligation whatsoever to provide any bug fixes, patches, or
upgrades to the features, functionality or performance of the source code
("Enhancements") to anyone; however, if you choose to make your Enhancements
available either publicly, or directly to Lawrence Berkeley National
Laboratory, without imposing a separate written license agreement for such
Enhancements, then you hereby grant the following license: a non-exclusive,
royalty-free perpetual license to install, use, modify, prepare derivative
works, incorporate into other computer software, distribute, and sublicense
such enhancements or derivative works thereof, in binary and source code form.
```

_The complete iperf3 license is available in the `LICENSE` file in the
top directory of the iperf3 source tree._

* Version of iperf3 (or development branch, such as `master` or
  `3.1-STABLE`) to which this pull request applies:

* Issues fixed (if any):

* Brief description of code changes (suitable for use as a commit message):

### CODE REVIEW

**Comment by bmah888** [comment]
Basic client/server testing between various combinations of cjson 1.7.13 and 1.7.15 seemed to work correctly. Also visually inspected `--json` output after a long-running test to confirm that long integers were represented correctly.

+1 to merge this.

**Review by bmah888 — APPROVED** [review]

**Comment by mickflemm** [comment]
I'm getting this error after the update: cjson.h:117:5: error: unknown type name 'int64_t'.

**Comment by swlars** [comment]
What OS are you testing with?

**Comment by mickflemm** [comment]
Linux 5.19, riscv64 with musl. I noticed you removed stdint.h from cjson.h, and then on https://github.com/esnet/iperf/blob/64db8f533055c5acbdcbc1d8beb0bce15f9e8ee9/src/cjson.h#L117 int64_t is still used so the compiler is correct, unless you get stdint.h from somewhere else the declaration is missing.  At the same time you've changed valueInt from int64_t to int in cjson.c and there is no usage of int64_t there, did you forget to update cjson.h line 117 and change update the structure declaration ?

**Pull request merged**
